[package]
name = "voxel_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
glfw = "0.56"
gl = "0.14"
glam = "0.29.2"
noise = "0.9"
image = "0.25"
log = "0.4"
env_logger = "0.11"
cgmath = "0.18"
rand = "0.8"


